### ISSUE TITLE
We need a KeyPair struct  or class for holding a public/private key pair

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#11]
See issue #10 .  A keypair needs the appropriate getter/setters and possibly some conversations to handle hex encoded output.  TBD.  Oddly, they don't publish all of their source, but there is a JS SDK available: https://github.com/QuantumMechanics/NEM-sdk/blob/master/src/crypto/keyPair.js

**Comment by truedat101** [comment]
We should convert this module into a proper class or set of utility functions.  Moving into proto3.

**Comment by truedat101** [comment]
I'll update this tomorrow.

**Comment by truedat101** [comment]
@acehreli welcome input on this one.  There is an ongoing set of thoughts on how to best design 

- utility functions
- factory stuff for crypto functions
- and whether to use simple structs as holders of things like Private key and public key pairs, or combine everything we need into classes

Since we have D we have ultimate flexibility.  The original Bitcoin stuff was designed in Python, later rewritten in C++.  The Ethereum core is C++ and some written on Golang, with a pretty nice set of Java bindings.  NEM is written in Java (the original code), the reference stuff in JS, and the new code in C++.  We find ourselves liking NEM a lot, but most of their open code is in JS, which is sort of an odd hybrid language.  We have a lot of flexibility to design however we'd like since we are going from scratch in D.

**Comment by truedat101** [comment]
And don't critique the existing design too hard.  It's skeletonware, an outline of a library with pieces being filled in slowly as we go along.

**Comment by pedroalvesbatista** [comment]
I created a method commitKeyPair for persisting the keypair for further recovery and use in other parts.

**Comment by truedat101** [comment]
I want to say this is covered by #10, that we've got a keypair.d .
