### ISSUE TITLE
proto2 needs unit tests

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#3]
Add a simple set of unit tests to each project .d file to incorporate unittest {} blocks.  Close this out when we've got 100% coverage.

**Comment by truedat101** [comment]
@pedroalvesbatista looks like you have a few build failures:

source\accountcore.d(15,5): Error: empty attribute list is not allowed
source\accountcore.d(15,5): Error: use @(attributes) instead of [attributes]
source\accountcore.d(16,1): Error: declaration expected, not }
source\blockcore.d(66,8): Error: found unittest instead of statement
source\blockcore.d(78,1): Error: unrecognized declaration

**Comment by truedat101** [comment]
@pedroalvesbatista Before we mark this phase as finished, please add unit tests to anything that is completed in proto2.

**Comment by davicitoafc** [comment]
@truedat101 You want me to test this or was this an accident?

**Comment by truedat101** [comment]
Sorry @davicitoafc accident.

**Comment by truedat101** [comment]
Moving out to proto3

**Comment by truedat101** [comment]
Mark this as done for proto2
