### ISSUE TITLE
Running dub test for rocksdb integration fails

### ISSUE THREAD

**Issue by pedroalvesbatista** [IoTone/TheShellProject#37]
The output of the error is the following :+1: 
No package file found in ./../../blockchain-sandbox/iotone.co/TheShellProject/shell-d/prototype/external/rocksdb/, expected one ofdub.json/dub.sdl/package.json

**Comment by truedat101** [comment]
I'll verify, I've never tested on linux.

**Comment by truedat101** [comment]
A bunch of path issues found.

**Comment by truedat101** [comment]
@pedroalvesbatista please update and retry.   The rocksdb build will take awhile.  When the build is done, you need to find the librocksdb.so file and copy it into the prototype directory.  Please confirm that this works for you.

**Comment by truedat101** [comment]
@pedroalvesbatista please take care of this, making sure you can build, because we cannot continue to have the build broken.  If you can't build then the code is only theoretical use.

**Comment by pedroalvesbatista** [comment]
I'm reviewing all the build issues, running the script worked fine, I also included the librocksdb.so into the protoype directory.

**Comment by truedat101** [comment]
ok, so does:

dub test work without failure?  If so, then rocksdb integration and libsodium is ok.

**Comment by pedroalvesbatista** [comment]
Yes, the integration is ok now ! I'll finish this issue

**Comment by truedat101** [comment]
Hmm, not sure how this was building for you, I found several issues.

**Comment by truedat101** [comment]
Let's leave stuff open until proven fixed / working / feature complete.

**Comment by pedroalvesbatista** [comment]
This still causes error, so we can deal with this as long we stay in the road ? I think the most crucial for the moment is the deimos.sodium integration to work fine because of the crypto stuff, the rocksdb we can stay a little off with it. Perhaps for proto3 we use it more directly.

**Comment by truedat101** [comment]
@pedroalvesbatista can you please indicate what the error is?

First make sure you can build.  dub build 

should build.  If you cannot build that is a different problem related to #38 .


Then run : dub test --compiler=gdc (or whatever compiler you use)

I expect that this should succeed, as I've tested on two different platforms.  However, if you get errors, please post the errors.  I cannot help if I cannot see the failures.

**Comment by truedat101** [comment]
Failure related to #41, seems like gdc offers different problems, or actually, some of these packages aren't fully supported on non-windows platforms.

**Comment by truedat101** [comment]
I think issues are resolved.

**Comment by pedroalvesbatista** [comment]
dub test
Generating test runner configuration 'shell-d-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using dmd for x86_64.
rocksdb ~master: target for configuration "library" is up to date.
shell-d ~master: building configuration "shell-d-test-library"...
Running pre-build commands...
Building the project
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./shell-d-test-library
./shell-d-test-library: error while loading shared libraries: librocksdb.so.5: cannot open shared object file: No such file or director
y
Program exited with code 127

**Comment by truedat101** [comment]
Ok, let me fix this.

**Comment by truedat101** [comment]
Pushed a fix.

**Comment by truedat101** [comment]
Problem on linux seems to be that it doesn't load the libraries properly.  Not sure if this is a problem with how we build the rocksdb library, but I think perhaps we need to look for something else.  Is there a pure D based database?  I'll mark that for proto3.

**Comment by truedat101** [comment]
Found the solution:

- remote librocksdb.* from your root of the project
- in your LD_LIBRARY_PATH set it to external/rocksdb-5.12.4/build .  Alternately, if you plan to copy files into your project root, you should only copy in: librocksdb.so.5.12.4, and softlink : ln -s librocksdb.so.5.12.4 ./librocksdb.so.5 , and then softlink : ln -s librocksdb.so.5 ./librocksdb.so
