### ISSUE TITLE
Provide estimates of effort (1,5,10,20,50)

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#39]
Apply points labels to estimate effort:

- 1 is hours of effort, maybe 1 -2 hours
- 5 is half day effort
- 10 is full day effort
- 20 is 2 day effort
- 50 is full week effort

**Comment by truedat101** [comment]
Before we start the next iteration we need to estimate the work.

**Comment by pedroalvesbatista** [comment]
50 - Full week effort
I'm adjusting my development cycle to not waste time with non-essential stuff and commit whatever I've be in

**Comment by truedat101** [comment]
Let's finish proto2 before we start on this.

**Comment by truedat101** [comment]
@pedroalvesbatista please put estimates on all proto3 items before you start.

**Comment by pedroalvesbatista** [comment]
50 - I dedicate the whole week for the project
