### ISSUE TITLE
Cleanup external dependencies

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#40]
- we shouldn't be checking in libraries that we are fetching via curl
- we want to avoid checking in large libraries that are big that we are not maintaining
- we should checkin libraries or patches if we intend to maintain the code ourselves
- please don't checkin .gz or zip or tar files of external dependencies

**Comment by pedroalvesbatista** [comment]
Right, will pay close attention only to source directory when pushing code.
