### ISSUE TITLE
Fix libsodium integration

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#43]
Demios doesn't ship binaries, but building with autotools makes me want to cry because they are brittle and often just don't work everywhere.  Either - prebuild for each supported platform (probably the answer) or switch to new build system.

**Comment by truedat101** [comment]
And the problem identified in #41 is that libsodium wrapper from demios doesn't provide a library prebuilt as it does for windows.

**Comment by truedat101** [comment]
I think this is resolved.  The LD_LIBRARY_PATH needs to be set.  If you've installed libsodium already, you can find them under /usr/local/lib.  So I would set export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by truedat101** [comment]
Verified this works with gdc on linux.

**Comment by truedat101** [comment]
@pedroalvesbatista please verify this works for you.

**Comment by pedroalvesbatista** [comment]
./shell-d: error while loading shared libraries: libsodium.so.23: cannot open shared object
file: No such file or directory

**Comment by truedat101** [comment]
From the readme: 
https://github.com/IoTone/TheShellProject/tree/proto2-dev/shell-d/prototype#building


    For libsodium, if you have built libsodium, point your LD_LIBRARY_PATH to libsodium. For a default linux install of libsodium, it would be under /usr/local/lib typically. Set: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib


Can you confirm if you have LD_LIBRARY_PATH set?

**Comment by pedroalvesbatista** [comment]
ALL UNIT TEST RUN SUCCESSFULLY

I MIGHT TELL THATS A GREEN LIGHT, RIGHT ?

**Comment by truedat101** [comment]
Ok, so this one is ok then.
