### ISSUE TITLE
Find D based alternative for pure D database or datastore

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#44]
We need something just written in D, very simple KV store or flat file database thing.

**Comment by truedat101** [comment]
This looks like all we need: https://github.com/cvsae/dddb

Maybe revisit taking on a leveldb wrapper project down the road.  For now this is good.

**Comment by truedat101** [comment]
BTW, not a fan of sqlite, and there are 3-5 generic db abstraction wrappers available already, anyone of which might work as a last resort.  Also, someone has a berkleydb wrapper.  Let's eliminate these complex integrations and just write stuff in D!

**Comment by pedroalvesbatista** [comment]
Yes, I think something in the BerkleyDB way in pure D is a good fit.

**Comment by pedroalvesbatista** [comment]
Hunts Labs has Neton, but it's merely for distributed systems

https://github.com/huntlabs/neton

**Comment by truedat101** [comment]
This solution probably doesn't work for any local services that would need to share a datastore, however, I think dddb is fine for now.  Note: I fixed leveldb #41 issues , however, we will leave it out for now.

**Comment by pedroalvesbatista** [comment]
Yeah, I agree, dddb is a good shot for now.
