### ISSUE TITLE
Progress and Updates on proto6

### ISSUE THREAD

**Issue by pedroalvesbatista** [IoTone/TheShellProject#53]

**Comment by pedroalvesbatista** [comment]
I'm getting through all the steps necessary to accomplish the algorithm

**Comment by pedroalvesbatista** [comment]
Included Project Design to general orientation.

**Comment by pedroalvesbatista** [comment]
Reestructure wiki for stuffs more close to building and kick start.

**Comment by pedroalvesbatista** [comment]
Describe in general steps that leads to the algorithms to used in the project as a whole.

**Comment by truedat101** [comment]
I think we can close this one out.
