### ISSUE TITLE
Project needs a standard approach for addresses

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#6]
Transactions and wallets have addresses.  We need a standard way to handle addressing.

Please reference details of NEM addressing: https://docs.nem.io/en/address-components

Let's borrow the best parts of this for the time being as an approach.  Please define an address struct that handles this format:

The address of an account is a base-32 encoded triplet consisting of:

    network byte: is it an address on the testnet or the mainnet?
    160-bit hash of the public key
    4 byte checksum, for detection of mistyped addresses

NEM's address api is defined here: https://www.nem.ninja/org.nem.core/org/nem/core/model/Address.html

**Comment by truedat101** [comment]
@pedroalvesbatista if you haven't started on this I can work on this.

**Comment by truedat101** [comment]
Related to #9 .  I think when #9 is done, we just need to take that data, and implement an Address struct or class.

**Comment by truedat101** [comment]
Not really sure if we need an Address class, but might be useful for handling basic operations on address.

**Comment by truedat101** [comment]
Punt out to proto3

**Comment by pedroalvesbatista** [comment]
Yeah, for addresses for now, yet, structs and basic ops should be enough. When working with peers and network maybe we need some class.

**Comment by pedroalvesbatista** [comment]
I added skeleton for functions to handle some basics of address approach. I will start to work more deeply on address while work on the hexdecimal hash generation.

**Comment by truedat101** [comment]
Wait so if we can generate an address, isn't this 100% done?

**Comment by truedat101** [comment]
I feel comfortable that we have a standard format.  This is enforced by KeyPairFactory.    Our spec/standard is: https://docs.nem.io/en/address-components

Marking this as done.

**Comment by truedat101** [comment]
Actually, leave this open.  The entire thing needs a test case.  See accountcore.d.

**Comment by truedat101** [comment]
Wow, accountcore.d is a mess.  No structure and no actual work done.

**Comment by truedat101** [comment]
ugg, seems like PB broke the dub.json.

**Comment by truedat101** [comment]
A basic test case is done.
