### ISSUE TITLE
Get rid of rocksdb if we aren't using it

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#64]
It's a dependency and it takes forever to build.  We don't use it so comment it out.

**Comment by pedroalvesbatista** [comment]
Is this out of the script ?

**Comment by truedat101** [comment]
Yes, already done, see commit 
c528263 

Marked as Needs Regression Testing so should be done.

**Comment by pedroalvesbatista** [comment]
Alright. Futurely perhaps we can go back and test this or a better DB other than dddb when we need more advanced features.

**Comment by truedat101** [comment]
I've added an issue for that (#67 ).
