### ISSUE TITLE
Fix build on dev branch

### ISSUE THREAD

**Issue by truedat101** [IoTone/TheShellProject#76]
Currently fails on m1 mac: dub build --compiler=ldc2

libkeccak-d ~master: building configuration "library"...
shell-d ~master: building configuration "application"...
Running pre-build commands...
Building the project
Linking...
ld: library not found for -lsodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
ldc2 failed with exit code 1.

**Comment by truedat101** [comment]
@pedroalvesbatista let me know what build error you are seeing.

**Comment by pedroalvesbatista** [comment]
Fail on Manjaro : `dub build --compiler=ldc2`

libkeccak-d ~master: building configuration "library"...
shell-d ~master: building configuration "application"...
Linking...
/usr/bin/ld.gold: error: cannot find -lkeccak-tiny
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
ldc2 failed with exit code 1.

**Comment by pedroalvesbatista** [comment]
Well, I ran git pull and could get Test RIPEMD and public key pair, as before.

**Comment by truedat101** [comment]
So be sure to run this first: sh ./setup-deps.sh

**Comment by truedat101** [comment]
That sets up the dependencies.

**Comment by pedroalvesbatista** [comment]
Yes, I ran the script and everything is fine by now.

**Comment by truedat101** [comment]
@pedroalvesbatista what platform are you on ? Linux?

**Comment by truedat101** [comment]
Dev branch building now, closing this out.
